### ISSUE TITLE
Rollback microflow tests after execution only works with a Setup microflow

### ISSUE THREAD

**Issue by CP-Fabian** [mendix/UnitTesting#19]
I have just completed the learning path 'Quality Control and Testing' and I noticed the behavior,that the entities I create within my microflow unittest doesn't rollback. According to the step description, the rollback should prevent all changes on my entities, but new entries are added and others are deleted after the tests run.

Apparently a transaction is only started if a **Setup** microflow is available in the module. I don't think this behavior is wanted.

I used Mendix Studio Pro 8.5.1, UnitTest 8.0.0 and ObjectHandling 3.0.0.

**Comment by WardBrink** [comment]
We are experiencing the same problems. Rollback does not seem to work at all.

**Comment by reinouts** [comment]
Hi @WardBrink and @CP-Fabian . I wish I could be of more help right now but I suggest you file a ticket with Mendix Support.

**Comment by WardBrink** [comment]
> Hi @WardBrink and @CP-Fabian . I wish I could be of more help right now but I suggest you file a ticket with Mendix Support.

Thanks for your reply! I created a Mendix support ticket.

**Comment by WernerGrobler** [comment]
We are experiencing the same issue. Also raised a support ticket, hopefully, they will get it fixed in the next release.

@WardBrink, I have tried adding the "Setup" microflow to the module in question, but it still seems not to roll back what was created in the UT. Am I missing something?
