### ISSUE TITLE
Commons HttpClient isn't packages with the module

### ISSUE THREAD

**Issue by KevinVlaanderen** [mendix/UnitTesting#2]
Buildfile: D:\Mendix Projects\Profile Service-412915-secure-profile-service\deployment\build_core.xml

compile:
    [javac] Compiling 139 source files to D:\Mendix Projects\Profile Service-412915-secure-profile-service\deployment\run\bin
    [javac] D:\Mendix Projects\Profile Service-412915-secure-profile-service\javasource\unittesting\RemoteApiServlet.java:8: error: package org.apache.commons.httpclient does not exist

**Comment by dlhartveld** [comment]
Additional info: Sprintr is using a slightly altered RemoteApiServlet which uses httpclient 4.x, which is better anyway, because it is supported and httpclient 3 is not anymore - please update to httpclient 4.latest.

**Comment by mafersolorzano** [comment]
Hi, I'm having the same issue, when trying to run the module within a Mendix Application. What should be updated?

**Comment by dlhartveld** [comment]
@mafersolorzano You can solve the issue for your project temporarily by downloading apache httpclient & httpcore 4.x jars and adding them to your userlib directory.

**Comment by RoelandSalij** [comment]
@mafersolorzano You can find the release which we are planning to publish in the App Store here:
https://github.com/mendix/UnitTesting/releases/tag/v4.1
