### ISSUE TITLE
The selected image 'NavigationLayouts.Images.logo' no longer exists.

### ISSUE THREAD

**Issue by WesselBraakman** [mendix/UnitTesting#20]
When using the UnitTesting module with Mendix Studio Pro v8.5 and 8.6.1 (I haven't checked newer versions), I get the following error:

`The selected image 'NavigationLayouts.Images.logo' no longer exists.`

This error is thrown on a button with the text "Bedrijfsnaam", located in UnitTesting/Private/NavigationLayouts/Sidebar_Full_Responsive.

**I get the error after freshly downloading the UnitTesting module from the app store.**

This error is resolved by picking any existing image from the dropdown menu.

![image](https://user-images.githubusercontent.com/16974850/75953342-78f89200-5eb1-11ea-95a1-1e61d03bc022.png)

**Comment by RoelandSalij** [comment]
Fixed, scheduled for release
