### ISSUE TITLE
Replace dependency on ObjectHandling by Communitycommons 

### ISSUE THREAD

**Issue by TimvanSteenbergen** [mendix/UnitTesting#36]
Is it an option to replace the dependency on ObjectHandling by one on Communitycommons? This is easily done by replacing:

> import ObjectHandling.XPath;

by

> import communitycommons.XPath;  

in two files: \javasource\unittesting\RemoteApiServlet.java and \javasource\unittesting\TestManager.java

This is something I do in every project the already uses CommunityCommons. Saves me importing ObjectHandling.

**Comment by MendixMurshed** [comment]
Hi Tim!

We have just released version 9.1.0 of the `UnitTesting` module that replaces the `ObjectHandling` module dependency with the `CommunityCommons` module: https://marketplace.mendix.com/link/component/390

Thank you for your feedback!
