### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by martijnraats** [mendix/UnitTesting#5]
Hello,

Why is the prefix changed from Test to Test_? (https://github.com/mendix/UnitTesting/commit/7daf92082b684cf1396cc0c2fc5842a95b09b1d6)
Now I need to change all my unit test microflow names, but besides that I like to use CamelCase for my microflow names, which for me do not include underscores.

Greetings Martijn

**Comment by RoelandSalij** [comment]
Hi, we got several complaints about the implementation which did not reflect the documentation and we corrected that in the latest version.
In a future version we'll make this prefix a constant which you can set in your own environment.

For now you can change https://github.com/mendix/UnitTesting/blob/master/src/javasource/unittesting/TestManager.java#L62 to Test to have it behave in the way you like.

**Comment by JefHellemansMendix** [comment]
Hi @martijnraats! My team at Mendix R&D recently added this module to our list of responsibilities. We do not have the time to put extensive work into it right now, but feel free to open a pull request for this issue if you are still interested in having it.
